language: common-lisp

branches:
  only:
    - master
    - develop
    - /^ci-.*$/

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=allegro
    - LISP=clisp
    - LISP=abcl

matrix:
  allow_failures:
    - env: LISP=allegro
    - env: LISP=clisp
    - env: LISP=abcl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros -s fiveam -e '(ql:quickload :dufy/test)
                      (or (fiveam:run! (quote dufy/test:main-suite))
                          (uiop:quit 1))'

sudo: required
