;;; -*- coding: utf-8 -*-
;;;
;;; This script file outputs the LCHab-to-Munsell data as a .lisp
;;; file.
;;;

(eval-when (:compile-toplevel :load-toplevel :execute)
  (ql:quickload '(:dufy/core :dufy/munsell :alexandria :iterate)))

(use-package '(:iterate :dufy/internal :dufy/munsell))

(defparameter *this-pathname* (uiop:current-lisp-file-pathname))

;; C*ab ∈ {0, 20, 40, ..., 500}
(defparameter number-of-cstars 26)

;;;
;;; Constructs LCHab-to-Munsell data.
;;;

;; hues and chromas
(defparameter inversed-mrd-table-hc
  (make-array (list 11 number-of-cstars 40 2)
              :element-type 'double-float))

;; values
(defparameter inversed-mrd-table-v
  (make-array 11 :element-type 'double-float))


(iter (for hab from 0 below 360 by 9)
      (iter (for lstar from 0 to 100 by 10)
            (iter (for cstarab from 0 to 500 by 20)
                  (multiple-value-bind (hue40 value chroma)
                      (lchab-to-mhvc-illum-c lstar cstarab hab
                                             :max-iteration 1000
                                             :factor 0.4d0
                                             :threshold 1d-13)
                    (let ((l-idx (/ lstar 10))
                          (c-idx (/ cstarab 20))
                          (h-idx (/ hab 9)))
                      (setf (aref inversed-mrd-table-hc l-idx c-idx h-idx 0) hue40
                            (aref inversed-mrd-table-v l-idx) value
                            (aref inversed-mrd-table-hc l-idx c-idx h-idx 1) chroma))))))

;;;
;;; Saves to the .lisp file.
;;;

(defun main (dest-filename)
  (let ((dest-path (uiop:merge-pathnames* dest-filename *this-pathname*)))
    (uiop:with-output-file (out dest-path :if-exists :supersede)
      (format out ";;; This file is automatically generated by ~a.~%~%"
              (file-namestring *this-pathname*))
      (format out "~S~%~%" '(in-package :dufy/munsell))
      (print-make-array "+inversed-mrd-table-hc+" inversed-mrd-table-hc out t)
      (print-make-array "+inversed-mrd-table-v+" inversed-mrd-table-v out t))
    (format t "The file is saved at ~A~%" dest-path)))

(main "inversed-renotation-data.lisp")

#-swank (uiop:quit)
  
