;;; This is a script file which generates fundamental data and saves them as a .lisp file.

(eval-when (:compile-toplevel :load-toplevel :execute)
  (ql:quickload '(:alexandria :dufy)))

(use-package :dufy/internal)

(defparameter *dat-path* (asdf:component-pathname (asdf:find-component "dufy" '("dat" "FL3.x.tsv"))))
(defparameter *dest-path* (uiop:merge-pathnames* "illuminants-f3-series.lisp" (uiop:current-lisp-file-pathname)))

(eval
 `(progn
    ,@(loop for idx from 1 to 15
            collect `(defparameter ,(intern (format nil "+F3.~A-TABLE+" idx))
                       (make-array 81 :element-type 'double-float)))))

(eval
 `(uiop:with-input-file (in *dat-path*)
    (let ((*read-default-float-format* 'double-float))
      (dotimes (wl-idx 81)
        (read in)
        ,@(loop for i from 1 to 15
                collect `(setf (aref ,(intern (format nil "+F3.~A-TABLE+" i)) wl-idx)
                               (coerce (read in) 'double-float)))))))


(uiop:with-output-file (out *dest-path* :if-exists :supersede)
  (format out ";;; This file is automatically generated by ~a.~%~%"
          (file-namestring (uiop:current-lisp-file-pathname)))
  (format out "~S~%~S~%~%"
          `(uiop:define-package :dufy/extra-data/illuminants-f3-series
             (:use :cl :dufy/core/*)
             (:export
              ,@(loop for i from 1 to 15
                      collect (make-symbol (format nil "+ILLUM-F3.~A+" i)))))
          `(in-package :dufy/extra-data/illuminants-f3-series))
  (format out "(eval-when (:compile-toplevel :load-toplevel :execute)~%")
  (loop for i from 1 to 15
        do (print-make-array (format nil "+F3.~A-TABLE+" i)
                             (eval (intern (format nil "+F3.~A-TABLE+" i)))
                             out t))
  (format out ")~%")
  (loop for i from 1 to 15
        do (print
            `(defparameter ,(intern (format nil "+ILLUM-F3.~A+" i))
               (dufy:make-illuminant :spectrum
                                     (dufy:gen-spectrum ,(intern (format nil "+F3.~A-TABLE+" i))
                                                        380 780)
                                     :begin-wl 380 :end-wl 780
                                     :compile-time t))
            out)
        finally (terpri out)))

(format t "The file is saved at ~A~%" *dest-path*)

#-swank (uiop:quit 1)
